version: '3.8'

services:
  api:
    image: nishant100606/viztube:latest
    restart: always
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
