version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: viztube_local_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_local_data:/var/lib/postgresql/data

volumes:
  postgres_local_data: